version: '3'

services:
  db:
    restart: always
    image: postgres:14-alpine
    user: postgres
    container_name: questions_app_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: questions_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pg_data: